// Mocks generated by Mockito 5.3.0 from annotations
// in ditonton/test/presentation/provider/detail_tvshow_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:ditonton/common/failure.dart' as _i6;
import 'package:ditonton/domain/entities/tvshow.dart' as _i9;
import 'package:ditonton/domain/entities/tvshow_detail.dart' as _i7;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i2;
import 'package:ditonton/domain/usecases/get_detail_tvshow.dart' as _i4;
import 'package:ditonton/domain/usecases/get_recommendation_tvshow.dart' as _i8;
import 'package:ditonton/domain/usecases/get_watchlist_byid_tvshow.dart'
    as _i10;
import 'package:ditonton/domain/usecases/insert_watchlist_tvshow.dart' as _i11;
import 'package:ditonton/domain/usecases/remove_watchlist_tvshow.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieRepository_0 extends _i1.SmartFake
    implements _i2.MovieRepository {
  _FakeMovieRepository_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [GetDetailTvShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDetailTvShow extends _i1.Mock implements _i4.GetDetailTvShow {
  MockGetDetailTvShow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
              returnValue:
                  _FakeMovieRepository_0(this, Invocation.getter(#repository)))
          as _i2.MovieRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.TvShowDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
              returnValue:
                  _i5.Future<_i3.Either<_i6.Failure, _i7.TvShowDetail>>.value(
                      _FakeEither_1<_i6.Failure, _i7.TvShowDetail>(
                          this, Invocation.method(#execute, [id]))))
          as _i5.Future<_i3.Either<_i6.Failure, _i7.TvShowDetail>>);
}

/// A class which mocks [GetRecommendationTvShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRecommendationTvShow extends _i1.Mock
    implements _i8.GetRecommendationTvShow {
  MockGetRecommendationTvShow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
              returnValue:
                  _FakeMovieRepository_0(this, Invocation.getter(#repository)))
          as _i2.MovieRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.TvShow>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
              returnValue:
                  _i5.Future<_i3.Either<_i6.Failure, List<_i9.TvShow>>>.value(
                      _FakeEither_1<_i6.Failure, List<_i9.TvShow>>(
                          this, Invocation.method(#execute, [id]))))
          as _i5.Future<_i3.Either<_i6.Failure, List<_i9.TvShow>>>);
}

/// A class which mocks [GetWatchListByIdTvShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListByIdTvShow extends _i1.Mock
    implements _i10.GetWatchListByIdTvShow {
  MockGetWatchListByIdTvShow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
              returnValue:
                  _FakeMovieRepository_0(this, Invocation.getter(#repository)))
          as _i2.MovieRepository);

  @override
  _i5.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: _i5.Future<bool>.value(false)) as _i5.Future<bool>);
}

/// A class which mocks [InsertWatchlistTvShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsertWatchlistTvShow extends _i1.Mock
    implements _i11.InsertWatchlistTvShow {
  MockInsertWatchlistTvShow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
              returnValue:
                  _FakeMovieRepository_0(this, Invocation.getter(#repository)))
          as _i2.MovieRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.TvShowDetail? tvShowDetail) =>
      (super.noSuchMethod(Invocation.method(#execute, [tvShowDetail]),
              returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
                  _FakeEither_1<_i6.Failure, String>(
                      this, Invocation.method(#execute, [tvShowDetail]))))
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistTvShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTvShow extends _i1.Mock
    implements _i12.RemoveWatchlistTvShow {
  MockRemoveWatchlistTvShow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
              returnValue:
                  _FakeMovieRepository_0(this, Invocation.getter(#repository)))
          as _i2.MovieRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.TvShowDetail? tvShowDetail) =>
      (super.noSuchMethod(Invocation.method(#execute, [tvShowDetail]),
              returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
                  _FakeEither_1<_i6.Failure, String>(
                      this, Invocation.method(#execute, [tvShowDetail]))))
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
}
