// Mocks generated by Mockito 5.3.0 from annotations
// in tvshow/test/presentation/pages/detail_tvshow_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:core/domain/entities/entities.dart' as _i3;
import 'package:core/utils/state_enum.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tvshow/domain/usecases/usecases.dart' as _i2;
import 'package:tvshow/presentation/provider/detail_tvshow_notifier.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetDetailTvShow_0 extends _i1.SmartFake
    implements _i2.GetDetailTvShow {
  _FakeGetDetailTvShow_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGetRecommendationTvShow_1 extends _i1.SmartFake
    implements _i2.GetRecommendationTvShow {
  _FakeGetRecommendationTvShow_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGetWatchListByIdTvShow_2 extends _i1.SmartFake
    implements _i2.GetWatchListByIdTvShow {
  _FakeGetWatchListByIdTvShow_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeInsertWatchlistTvShow_3 extends _i1.SmartFake
    implements _i2.InsertWatchlistTvShow {
  _FakeInsertWatchlistTvShow_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistTvShow_4 extends _i1.SmartFake
    implements _i2.RemoveWatchlistTvShow {
  _FakeRemoveWatchlistTvShow_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTvShowDetail_5 extends _i1.SmartFake implements _i3.TvShowDetail {
  _FakeTvShowDetail_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [DetailTvShowNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetailTvShowNotifier extends _i1.Mock
    implements _i4.DetailTvShowNotifier {
  MockDetailTvShowNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetDetailTvShow get getDetailTvShow => (super.noSuchMethod(
          Invocation.getter(#getDetailTvShow),
          returnValue:
              _FakeGetDetailTvShow_0(this, Invocation.getter(#getDetailTvShow)))
      as _i2.GetDetailTvShow);

  @override
  _i2.GetRecommendationTvShow get getRecommendationTvShow =>
      (super.noSuchMethod(Invocation.getter(#getRecommendationTvShow),
              returnValue: _FakeGetRecommendationTvShow_1(
                  this, Invocation.getter(#getRecommendationTvShow)))
          as _i2.GetRecommendationTvShow);

  @override
  _i2.GetWatchListByIdTvShow get getWatchListByIdTvShow =>
      (super.noSuchMethod(Invocation.getter(#getWatchListByIdTvShow),
              returnValue: _FakeGetWatchListByIdTvShow_2(
                  this, Invocation.getter(#getWatchListByIdTvShow)))
          as _i2.GetWatchListByIdTvShow);

  @override
  _i2.InsertWatchlistTvShow get insertWatchlistTvShow =>
      (super.noSuchMethod(Invocation.getter(#insertWatchlistTvShow),
              returnValue: _FakeInsertWatchlistTvShow_3(
                  this, Invocation.getter(#insertWatchlistTvShow)))
          as _i2.InsertWatchlistTvShow);

  @override
  _i2.RemoveWatchlistTvShow get removeWatchlistTvShow =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlistTvShow),
              returnValue: _FakeRemoveWatchlistTvShow_4(
                  this, Invocation.getter(#removeWatchlistTvShow)))
          as _i2.RemoveWatchlistTvShow);

  @override
  _i3.TvShowDetail get detailTvShow =>
      (super.noSuchMethod(Invocation.getter(#detailTvShow),
              returnValue:
                  _FakeTvShowDetail_5(this, Invocation.getter(#detailTvShow)))
          as _i3.TvShowDetail);

  @override
  _i5.RequestState get tvShowState =>
      (super.noSuchMethod(Invocation.getter(#tvShowState),
          returnValue: _i5.RequestState.Empty) as _i5.RequestState);

  @override
  List<_i3.TvShow> get tvShowRecommendations =>
      (super.noSuchMethod(Invocation.getter(#tvShowRecommendations),
          returnValue: <_i3.TvShow>[]) as List<_i3.TvShow>);

  @override
  _i5.RequestState get recommendationState =>
      (super.noSuchMethod(Invocation.getter(#recommendationState),
          returnValue: _i5.RequestState.Empty) as _i5.RequestState);

  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);

  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(Invocation.getter(#isAddedToWatchlist),
          returnValue: false) as bool);

  @override
  String get watchlistMessage =>
      (super.noSuchMethod(Invocation.getter(#watchlistMessage), returnValue: '')
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> fetchDetailTvShow(int? id) => (super.noSuchMethod(
      Invocation.method(#fetchDetailTvShow, [id]),
      returnValue: _i6.Future<void>.value(),
      returnValueForMissingStub: _i6.Future<void>.value()) as _i6.Future<void>);

  @override
  _i6.Future<void> addWatchlist(_i3.TvShowDetail? tvShowDetail) =>
      (super.noSuchMethod(Invocation.method(#addWatchlist, [tvShowDetail]),
              returnValue: _i6.Future<void>.value(),
              returnValueForMissingStub: _i6.Future<void>.value())
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeFromWatchlist(_i3.TvShowDetail? tvShowDetail) => (super
          .noSuchMethod(Invocation.method(#removeFromWatchlist, [tvShowDetail]),
              returnValue: _i6.Future<void>.value(),
              returnValueForMissingStub: _i6.Future<void>.value())
      as _i6.Future<void>);

  @override
  _i6.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
      Invocation.method(#loadWatchlistStatus, [id]),
      returnValue: _i6.Future<void>.value(),
      returnValueForMissingStub: _i6.Future<void>.value()) as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);

  @override
  void removeListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);

  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);

  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
